// <auto-generated />
namespace VJP_Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Event_Project : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Event_Project));
        
        string IMigrationMetadata.Id
        {
            get { return "201808131244458_Event_Project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
