// <auto-generated />
namespace VJP_Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class STD_JUGE_EDU_EXP_Add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(STD_JUGE_EDU_EXP_Add));
        
        string IMigrationMetadata.Id
        {
            get { return "201807281946365_STD_JUGE_EDU_EXP_Add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
